import { formatOklch } from './color.js';

const cssName = (name, family = 'primary') => `--brand-${family}${name === 'default' ? '' : `-${name}`}`;
const number = (value) => `${value >= 0 ? '+' : ''}${value.toFixed(6)}`;
const status = (value, passes) => `${value.toFixed(4)}:1 ${passes ? 'PASS' : 'FAIL'}`;

export function renderCss(result) {
  const states = { primary: result, secondary: result.secondary };
  return [
    '/* Generated by Brand Token Generator v1.1. Edit config.json, then regenerate.',
    ` * Source Primary: ${result.primary}. Source Secondary: ${result.secondary.sourceHex}.`,
    ` * Used state-text contrast target: ${result.config.minContrast}:1.`,
    ' * Each 11-tone palette: every gap >= 5 passes 4.5:1 using these exact HEX values.',
    ' * Source colors and state tokens are separate from the numbered palette rule.',
    ...result.warnings.map((warning) => ` * NOTE: ${warning}`),
    ' */', ':root {',
    `  --brand-primary-source: ${result.primary}; /* Original identity color; check contrast before use. */`,
    `  --brand-secondary-source: ${result.secondary.sourceHex};`, '',
    ...Object.entries(result.palettes).flatMap(([family, palette]) => [
      `  /* ${family}: minimum verified gap >= 5 contrast ${palette.minimumActualContrast.toFixed(4)}:1. */`,
      ...palette.tones.flatMap((tone) => [
        `  --brand-${family}-${tone.level}: ${tone.hex}; /* target vs white ${tone.targetContrast.toFixed(4)}:1; actual ${tone.contrast.white.toFixed(4)}:1; ${formatOklch(tone.oklch)} */`,
        `  --brand-on-${family}-${tone.level}: ${tone.text}; /* text ${status(tone.contrast.selected, tone.passes.selected)} at ${palette.textMinContrast}:1 target */`,
      ]), '',
    ]),
    ...Object.entries(states).flatMap(([family, group]) => [
      `  /* ${family} interaction states: compatible with v1.0 Primary behavior. */`,
      ...group.tokens.map((token) => `  ${cssName(token.name, family)}: ${token.hex}; /* ${formatOklch(token.oklch)} */`),
      `  --brand-on-${family}: ${group.solidText};`,
      `  --brand-on-${family}-subtle: #000000;`, '',
    ]),
    '}', '',
  ].join('\n');
}

function paletteMarkdown(family, palette) {
  return [
    `## ${family} 11-tone palette`, '',
    `Source: \`${palette.sourceHex}\`. Nearest level by white contrast: **${palette.nearestLevel}** (not an exact source-color match).`,
    `Minimum actual contrast across all ${palette.pairs.length} eligible pairs: **${palette.minimumActualContrast.toFixed(4)}:1**.`, '',
    '| Level | Final HEX | Target on white | Actual on white | Black text | Best text | Best-text target |',
    '| --- | --- | --- | --- | --- | --- | --- |',
    ...palette.tones.map((tone) => `| ${tone.level} | ${tone.hex} | ${tone.targetContrast.toFixed(4)}:1 | ${status(tone.contrast.white, tone.passes.white)} | ${status(tone.contrast.black, tone.passes.black)} | ${tone.text} | ${status(tone.contrast.selected, tone.passes.selected)} |`), '',
    'Targets use white as the reference; PASS/FAIL in the text columns uses the configured text threshold.',
    'The stored HEX is the closest searched color to the continuous contrast target, so target and actual may differ slightly.', '',
    '**한국어 설명**', '',
    '흰색 기준 목표 대비율에 맞춘 11단계입니다. 목표값과 최종 HEX의 실제 대비율을 함께 표시합니다. Best text는 흰색·검정 중 대비가 높은 색이며, 통과 표시는 설정한 텍스트 대비 기준으로 판정합니다.', '',
    '### Five-step pair checks', '',
    '| Lighter level | Darker level | Step gap | Actual contrast | Result |',
    '| --- | --- | --- | --- | --- |',
    ...palette.pairs.map((pair) => `| ${pair.from} | ${pair.to} | ${pair.gap} | ${pair.ratio.toFixed(4)}:1 | ${pair.passes ? 'PASS' : 'FAIL'} |`), '',
    'Step gap counts positions in the 11-level list, not subtraction of numeric token labels.',
    'The 4.5:1 guarantee applies within this palette. It does not automatically cover original source colors, state tokens, or arbitrary mixtures with the other palette.', '',
    '**한국어 설명**', '',
    '5레벨 차이는 목록에서 다섯 칸 떨어진 관계입니다. 예: 50↔500, 100↔600, 500↔950. 5단계 이상 떨어진 21개 조합을 최종 HEX로 검사합니다. 원본 색상·상태 색상·Primary와 Secondary를 섞은 조합은 별도로 검사해야 합니다.', '',
  ];
}

function stateMarkdown(family, group) {
  return [
    `## ${family} state tokens`, '',
    `Solid text: \`${group.solidText}\`. Solid L shift: **${number(group.solidShift)}**. Subtle text: \`#000000\`.`, '',
    '| State | Initial HEX | Final HEX | White text | Black text | Best text | Used text |',
    '| --- | --- | --- | --- | --- | --- | --- |',
    ...group.tokens.map((token) => `| ${token.name} | ${token.candidateHex} | ${token.hex} | ${status(token.contrast.white, token.passes.white)} | ${status(token.contrast.black, token.passes.black)} | ${token.recommendedText}${token.recommendedPasses ? '' : ' (below target)'} | ${token.text} |`), '',
    '| State | Final OKLCH (from saved HEX) | L shift | HEX changed | Final gamut reduction |',
    '| --- | --- | --- | --- | --- |',
    ...group.tokens.map((token) => `| ${token.name} | ${formatOklch(token.oklch)} | ${number(token.lightnessShift)} | ${token.adjusted ? 'Yes' : 'No'} | ${token.gamutReduced ? 'Yes' : 'No'} |`), '',
    'State generation preserves v1.0 behavior: Default starts at the source, Hover/Pressed use the configured L deltas. If needed, shift the solid ramp together to pass the used-text target.', '',
    '**한국어 설명**', '',
    '기존 상태 컬러 생성 방식을 유지합니다. 원본에서 Hover·Pressed 명도를 낮추고, 사용하는 텍스트 대비가 부족하면 상태 색상의 명도를 함께 보정합니다. 상태 컬러와 11단계 팔레트는 별도로 출력합니다.', '',
  ];
}

export function renderMarkdown(result) {
  return [
    '# Brand tokens v1.1', '',
    '## Generation summary', '',
    `- Source Primary: \`${result.primary}\` (${formatOklch(result.primaryOklch)})`,
    `- Source Secondary: \`${result.secondary.sourceHex}\` (${result.secondary.mode}${result.secondary.hueOffset === null ? '' : `, hue offset ${result.secondary.hueOffset}°`})`,
    `- Contrast target: **${result.config.minContrast}:1** for state text and palette best-text checks.`,
    '- Palette pair rule: **step gap ≥ 5 → actual contrast ≥ 4.5:1**, separately for Primary and Secondary.',
    '- All PASS/FAIL results use unrounded ratios; displayed numbers are rounded.', '',
    'The 11 target ratios against white are 21^(index/10), for indices 0 through 10. Continuous five-step ratios are √21 ≈ 4.5826:1; every eligible final HEX pair is checked independently.',
    'Levels 50 and 950 are white and black endpoints. Source colors are preserved separately and are not forced into level 500.', '',
    '**한국어 설명**', '',
    'Primary·Secondary를 각각 11단계로 생성합니다. 흰색 기준 목표 대비율로 단계를 정한 뒤, 같은 팔레트에서 5단계 이상 떨어진 모든 색상 조합이 최소 4.5:1인지 최종 HEX로 검사합니다. 양 끝은 흰색·검정이며 원본 색상은 별도로 보존합니다.', '',
    ...paletteMarkdown('Primary', result.palettes.primary),
    ...paletteMarkdown('Secondary', result.palettes.secondary),
    ...stateMarkdown('Primary', result),
    ...stateMarkdown('Secondary', result.secondary),
    '## Notes', '',
    ...(result.warnings.length ? result.warnings.map((warning) => `- ${warning}`) : ['- No warnings.']),
    '- Automatic Secondary is a hue-based suggestion; visual harmony still depends on the project. Override it with an explicit HEX when needed.',
    '- Hue is held during generation; chroma decreases for sRGB. Rounded HEX can slightly change measured OKLCH.',
    '- Checks cover opaque, solid-color pairs. Recheck opacity, gradients, images, different foregrounds, and cross-palette combinations.',
    '- No Base Design System, neutral, semantic-status, or focus values are generated or modified.', '',
    '**한국어 설명**', '',
    '자동 Secondary는 색상 각도 기반 제안입니다. 프로젝트 분위기에 맞는지 확인하고 직접 HEX를 지정할 수 있습니다. 이 결과는 브랜드용 토큰이며 Base Design System과 승인된 중립·상태·포커스 규칙을 변경하지 않습니다.', '',
    '## References', '',
    '- [WCAG 2.2 text contrast](https://www.w3.org/TR/WCAG22/#contrast-minimum)',
    '- [WCAG relative luminance](https://www.w3.org/TR/WCAG22/#dfn-relative-luminance)',
    '- [Oklab conversion by Björn Ottosson](https://bottosson.github.io/posts/oklab/)', '',
    '**한국어 설명**', '',
    '대비율은 WCAG 상대 휘도 공식을 사용하며, 색상 변환은 Oklab 변환 행렬을 사용합니다.', '',
  ].join('\n');
}
