import { formatOklch } from './color.js';

const cssName = (name, family = 'primary') => `--brand-${family}${name === 'default' ? '' : `-${name}`}`;
const number = (value) => `${value >= 0 ? '+' : ''}${value.toFixed(6)}`;
const status = (value, passes) => `${value.toFixed(4)}:1 ${passes ? 'PASS' : 'FAIL'}`;

export function renderCss(result) {
  const states = { primary: result, secondary: result.secondary };
  return [
    '/* Generated by Brand Token Generator v1.2. Edit config.json, then regenerate.',
    ` * Source Primary: ${result.primary}. Source Secondary: ${result.secondary.sourceHex}.`,
    ` * Used state-text contrast target: ${result.config.minContrast}:1.`,
    ' * Magic number = grade difference: 40+ >= 3:1; 50+ >= 4.5:1; 70+ >= 7:1; 90+ >= 15:1.',
    ' * Audited within Primary/Secondary and across both generated grade palettes.',
    ' * Eleven brand grades (5-95) plus endpoints 0 (white) and 100 (black).',
    ' * Source colors and state tokens are separate from the numbered palette rule.',
    ...result.warnings.map((warning) => ` * NOTE: ${warning}`),
    ' */', ':root {',
    `  --brand-primary-source: ${result.primary}; /* Original identity color; check contrast before use. */`,
    `  --brand-secondary-source: ${result.secondary.sourceHex};`, '',
    ...Object.entries(result.palettes).flatMap(([family, palette]) => [
      `  /* ${family}: all four magic-number rules verified. */`,
      ...palette.tones.flatMap((tone) => [
        `  --brand-${family}-grade-${tone.level}: ${tone.hex}; /* target vs white ${tone.targetContrast.toFixed(4)}:1; actual ${tone.contrast.white.toFixed(4)}:1; ${formatOklch(tone.oklch)} */`,
        `  --brand-on-${family}-grade-${tone.level}: ${tone.text}; /* text ${status(tone.contrast.selected, tone.passes.selected)} at ${palette.textMinContrast}:1 target */`,
      ]), '',
    ]),
    ...Object.entries(states).flatMap(([family, group]) => [
      `  /* ${family} interaction states: compatible with v1.0 Primary behavior. */`,
      ...group.tokens.map((token) => `  ${cssName(token.name, family)}: ${token.hex}; /* ${formatOklch(token.oklch)} */`),
      `  --brand-on-${family}: ${group.solidText};`,
      `  --brand-on-${family}-subtle: #000000;`, '',
    ]),
    '}', '',
  ].join('\n');
}

function ruleSummaryMarkdown(summary) {
  return [
    '| Minimum grade difference | Required contrast | Checked pairs | Lowest actual contrast | Result |',
    '| --- | --- | --- | --- | --- |',
    ...summary.map((rule) => `| ${rule.magicNumber} | ${rule.minContrast}:1 | ${rule.pairCount} | ${rule.minimumActualContrast.toFixed(4)}:1 | ${rule.passes ? 'PASS' : 'FAIL'} |`), '',
  ];
}

function pairTable(pairs) {
  return [
    '| First grade | Second grade | Magic number | Required contrast | Actual contrast | Result |',
    '| --- | --- | --- | --- | --- | --- |',
    ...pairs.map((pair) => `| ${pair.from} | ${pair.to} | ${pair.gap} | ${pair.requiredContrast}:1 | ${pair.ratio.toFixed(4)}:1 | ${pair.passes ? 'PASS' : 'FAIL'} |`), '',
  ];
}

function paletteMarkdown(family, palette) {
  return [
    `## ${family} grade palette`, '',
    `Source: \`${palette.sourceHex}\`. Nearest level by white contrast: **${palette.nearestLevel}** (not an exact source-color match).`,
    `Eleven brand grades plus two endpoints. All ${palette.pairs.length} eligible pairs meet their applicable rule.`, '',
    ...ruleSummaryMarkdown(palette.ruleSummary),
    '| Level | Final HEX | Target on white | Actual on white | Black text | Best text | Best-text target |',
    '| --- | --- | --- | --- | --- | --- | --- |',
    ...palette.tones.map((tone) => `| ${tone.level} | ${tone.hex} | ${tone.targetContrast.toFixed(4)}:1 | ${status(tone.contrast.white, tone.passes.white)} | ${status(tone.contrast.black, tone.passes.black)} | ${tone.text} | ${status(tone.contrast.selected, tone.passes.selected)} |`), '',
    'Targets use white as the reference; PASS/FAIL in the text columns uses the configured text threshold.',
    'The stored HEX is the closest searched color to the continuous contrast target, so target and actual may differ slightly.', '',
    '**한국어 설명**', '',
    '브랜드 색상 11단계(5–95)와 흰색·검정 기준점(0·100)입니다. 매직넘버는 등급 숫자의 차이이며 칸 수나 실제 명도 퍼센트가 아닙니다. Best text는 흰색·검정 중 대비가 높은 색이고, 텍스트 통과 표시는 별도 설정 기준으로 판정합니다.', '',
    '### Grade luminance targets', '',
    '| Grade | Allowed relative luminance | Target luminance | Actual HEX luminance |',
    '| --- | --- | --- | --- |',
    ...palette.tones.map((tone) => `| ${tone.level} | ${tone.luminanceBand[0].toFixed(3)}–${tone.luminanceBand[1].toFixed(3)} | ${tone.targetLuminance.toFixed(6)} | ${tone.luminance.toFixed(6)} |`), '',
    'The grade-95 band (0.002–0.004) is a local extension. Other bands use the USWDS grade-luminance table.', '',
    '**한국어 설명**', '',
    '등급별 상대 휘도 범위를 기준으로 OKLCH 명도를 조정합니다. 95등급의 0.002–0.004 범위는 이번 도구의 확장값이며, 최종 HEX로 네 가지 매직넘버 규칙을 모두 검사합니다.', '',
    '### Magic-number pair checks', '',
    ...pairTable(palette.pairs),
    'Magic number is the absolute numeric grade difference. The table displays the strongest applicable threshold.',
    'Summary counts overlap: a difference of 90 also satisfies the lower 40/50/70 rules.', '',
    '**한국어 설명**', '',
    '예: 0↔50은 매직넘버 50으로 최소 4.5:1, 10↔80은 매직넘버 70으로 최소 7:1입니다. 표에는 해당 조합의 가장 높은 대비 기준을 표시합니다. 원본·상태 색상에는 이 등급 규칙을 자동 적용하지 않습니다.', '',
  ];
}

function stateMarkdown(family, group) {
  return [
    `## ${family} state tokens`, '',
    `Solid text: \`${group.solidText}\`. Solid L shift: **${number(group.solidShift)}**. Subtle text: \`#000000\`.`, '',
    '| State | Initial HEX | Final HEX | White text | Black text | Best text | Used text |',
    '| --- | --- | --- | --- | --- | --- | --- |',
    ...group.tokens.map((token) => `| ${token.name} | ${token.candidateHex} | ${token.hex} | ${status(token.contrast.white, token.passes.white)} | ${status(token.contrast.black, token.passes.black)} | ${token.recommendedText}${token.recommendedPasses ? '' : ' (below target)'} | ${token.text} |`), '',
    '| State | Final OKLCH (from saved HEX) | L shift | HEX changed | Final gamut reduction |',
    '| --- | --- | --- | --- | --- |',
    ...group.tokens.map((token) => `| ${token.name} | ${formatOklch(token.oklch)} | ${number(token.lightnessShift)} | ${token.adjusted ? 'Yes' : 'No'} | ${token.gamutReduced ? 'Yes' : 'No'} |`), '',
    'State generation preserves v1.0 behavior: Default starts at the source, Hover/Pressed use the configured L deltas. If needed, shift the solid ramp together to pass the used-text target.', '',
    '**한국어 설명**', '',
    '기존 상태 컬러 생성 방식을 유지합니다. 원본에서 Hover·Pressed 명도를 낮추고, 사용하는 텍스트 대비가 부족하면 상태 색상의 명도를 함께 보정합니다. 상태 컬러와 11단계 팔레트는 별도로 출력합니다.', '',
  ];
}

export function renderMarkdown(result) {
  return [
    '# Brand tokens v1.2', '',
    '## Generation summary', '',
    `- Source Primary: \`${result.primary}\` (${formatOklch(result.primaryOklch)})`,
    `- Source Secondary: \`${result.secondary.sourceHex}\` (${result.secondary.mode}${result.secondary.hueOffset === null ? '' : `, hue offset ${result.secondary.hueOffset}°`})`,
    `- Contrast target: **${result.config.minContrast}:1** for state text and palette best-text checks.`,
    '- Magic number: **absolute numeric grade difference**, not a count of positions.',
    '- Rules: **40+ → 3:1; 50+ → 4.5:1; 70+ → 7:1; 90+ → 15:1**.',
    '- Verified scopes: Primary, Secondary, and mixed Primary/Secondary grade pairs.',
    '- All PASS/FAIL results use unrounded ratios; displayed numbers are rounded.', '',
    'Brand grades: 5 / 10 / 20 / 30 / 40 / 50 / 60 / 70 / 80 / 90 / 95. Add grade 0 (white) and 100 (black).',
    'Source colors are preserved separately and are not forced into grade 50. CSS uses the new grade namespace: --brand-primary-grade-50.', '',
    '**한국어 설명**', '',
    '브랜드 팔레트는 5–95의 11단계이며, 0(흰색)과 100(검정)을 추가합니다. 칸 수가 아니라 등급 숫자 차이 40·50·70·90으로 대비 기준을 판정합니다. 같은 팔레트와 Primary·Secondary 혼합 조합을 모두 최종 HEX로 검사합니다.', '',
    ...paletteMarkdown('Primary', result.palettes.primary),
    ...paletteMarkdown('Secondary', result.palettes.secondary),
    '## Mixed Primary/Secondary checks', '',
    'First grade belongs to Primary; second grade belongs to Secondary. Only generated grades are included.', '',
    ...ruleSummaryMarkdown(result.crossRuleSummary),
    ...pairTable(result.crossPairs),
    '**한국어 설명**', '',
    '첫 번째 등급은 Primary, 두 번째 등급은 Secondary입니다. 두 팔레트를 섞어 사용할 때도 동일한 네 가지 매직넘버 규칙을 검사합니다. 원본·상태 색상과 기존 Neutral 토큰은 이 등급 체계에 포함되지 않습니다.', '',
    ...stateMarkdown('Primary', result),
    ...stateMarkdown('Secondary', result.secondary),
    '## Notes', '',
    ...(result.warnings.length ? result.warnings.map((warning) => `- ${warning}`) : ['- No warnings.']),
    '- Automatic Secondary is a hue-based suggestion; visual harmony still depends on the project. Override it with an explicit HEX when needed.',
    '- Hue is held during generation; chroma decreases for sRGB. Rounded HEX can slightly change measured OKLCH.',
    '- Checks cover these generated opaque grade pairs. Recheck opacity, gradients, images, source/state colors, and other foregrounds.',
    '- No Base Design System, neutral, semantic-status, or focus values are generated or modified.', '',
    '**한국어 설명**', '',
    '자동 Secondary는 색상 각도 기반 제안입니다. 프로젝트 분위기에 맞는지 확인하고 직접 HEX를 지정할 수 있습니다. 이 결과는 브랜드용 토큰이며 Base Design System과 승인된 중립·상태·포커스 규칙을 변경하지 않습니다.', '',
    '## References', '',
    '- [KRDS color and magic numbers](https://www.krds.go.kr/html/site/style/style_02.html)',
    '- [USWDS grade luminance bands](https://designsystem.digital.gov/design-tokens/color/overview/#magic-number)',
    '- [WCAG 2.2 text contrast](https://www.w3.org/TR/WCAG22/#contrast-minimum)',
    '- [WCAG relative luminance](https://www.w3.org/TR/WCAG22/#dfn-relative-luminance)',
    '- [Oklab conversion by Björn Ottosson](https://bottosson.github.io/posts/oklab/)', '',
    '**한국어 설명**', '',
    '대비율은 WCAG 상대 휘도 공식을 사용하며, 색상 변환은 Oklab 변환 행렬을 사용합니다.', '',
  ].join('\n');
}
