import { formatOklch } from './color.js';

const cssName = (name) => name === 'default' ? '--brand-primary' : `--brand-primary-${name}`;
const number = (value) => `${value >= 0 ? '+' : ''}${value.toFixed(6)}`;

export function renderCss(result) {
  const { tokens, primary, solidText, config } = result;
  return [
    '/* Generated by Brand Token Generator. Edit config.json, then regenerate.',
    ` * Source Primary: ${primary}. Selected text contrast target: ${config.minContrast}:1.`,
    ' * HEX values below are the exact colors audited; OKLCH comments are descriptive.',
    ...result.warnings.map((warning) => ` * NOTE: ${warning}`),
    ' */', ':root {',
    ...tokens.map((token) => `  ${cssName(token.name)}: ${token.hex}; /* ${formatOklch(token.oklch)} */`),
    `  --brand-on-primary: ${solidText};`,
    '  --brand-on-primary-subtle: #000000;',
    '}', '',
  ].join('\n');
}

export function renderMarkdown(result) {
  const { config, tokens } = result;
  const status = (value, passes) => `${value.toFixed(4)}:1 ${passes ? 'PASS' : 'FAIL'}`;
  return [
    '# Brand tokens', '',
    `- Source Primary: \`${result.primary}\` (${formatOklch(result.primaryOklch)})`,
    `- Contrast target: **${config.minContrast}:1**`,
    `- Solid text: \`${result.solidText}\`; Subtle text: \`#000000\``,
    `- Solid ramp lightness shift: **${number(result.solidShift)}** (absolute OKLCH L units).`, '',
    '## Final tokens', '',
    '| State | Initial HEX | Final HEX | White text | Black text | Best text | Used text |',
    '| --- | --- | --- | --- | --- | --- | --- |',
    ...tokens.map((token) => `| ${token.name} | ${token.candidateHex} | ${token.hex} | ${status(token.contrast.white, token.passes.white)} | ${status(token.contrast.black, token.passes.black)} | ${token.recommendedText}${token.recommendedPasses ? '' : ' (below target)'} | ${token.text} |`), '',
    'PASS/FAIL uses unrounded ratios. Displayed ratios are rounded for reading.',
    'White and black are alternative foregrounds; they are not both required to pass.',
    'Best text is the higher-contrast choice per state. Used text stays consistent across the solid states.', '',
    '## Conversion and adjustments', '',
    '| State | Final OKLCH (from saved HEX) | L shift | HEX changed | Final gamut reduction |',
    '| --- | --- | --- | --- | --- |',
    ...tokens.map((token) => `| ${token.name} | ${formatOklch(token.oklch)} | ${number(token.lightnessShift)} | ${token.adjusted ? 'Yes' : 'No'} | ${token.gamutReduced ? 'Yes' : 'No'} |`), '',
    'Initial candidates: Default = source Primary, Hover = L − hoverDelta, Pressed = L − pressedDelta; L is clamped to 0–1.',
    `Subtle = L ${config.subtleLightness}, source chroma × ${config.subtleChromaFactor}.`,
    'If needed, the entire solid ramp shifts toward black for white text or toward white for black text. Subtle only shifts toward white for black text.',
    'Hue stays fixed during adjustment; chroma decreases when needed for sRGB. Rounded HEX conversion can slightly change the measured OKLCH.', '',
    '## Notes', '',
    ...(result.warnings.length ? result.warnings.map((warning) => `- ${warning}`) : ['- No warnings.']),
    '- These checks cover opaque text on the exact token background. Recheck transparency, gradients, images, and other foregrounds.',
    '- Text contrast alone does not verify focus rings, component boundaries, or overall accessibility.', '',
    '## References', '',
    '- [WCAG 2.2 text contrast](https://www.w3.org/TR/WCAG22/#contrast-minimum)',
    '- [WCAG relative luminance](https://www.w3.org/TR/WCAG22/#dfn-relative-luminance)',
    '- [Oklab conversion by Björn Ottosson](https://bottosson.github.io/posts/oklab/)', '',
  ].join('\n');
}
